export const Duplicate = [
  {
    id: "0",
    Employee: "Alejandro Escamilla",
    width: 5000,
    height: 3333,
    url: "https://unsplash.com/photos/yC-Yzbqy7PY",
    download_url: "https://picsum.photos/id/0/5000/3333",
    totaltimeloged: 123,
    currentStatus: 1,
  },
  {
    id: "1",
    Employee: "Alejandro Escamilla",
    width: 5000,
    height: 3333,
    url: "https://unsplash.com/photos/LNRyGwIJr5c",
    download_url: "https://picsum.photos/id/1/5000/3333",
    totaltimeloged: 456,
    currentStatus: 0,
  },
  {
    id: "3",
    Employee: "Alejandro Escamilla",
    width: 5000,
    height: 3333,
    url: "https://unsplash.com/photos/Dl6jeyfihLk",
    download_url: "https://picsum.photos/id/3/5000/3333",
    totaltimeloged: 101,
    currentStatus: 0,
  },
  {
    id: "7",
    Employee: "Alejandro Escamilla",
    width: 4728,
    height: 3168,
    url: "https://unsplash.com/photos/BbQLHCpVUqA",
    download_url: "https://picsum.photos/id/7/4728/3168",
    totaltimeloged: 112,
    currentStatus: 0,
  },
  {
    id: "9",
    Employee: "Alejandro Escamilla",
    width: 5000,
    height: 3269,
    url: "https://unsplash.com/photos/ABDTiLqDhJA",
    download_url: "https://picsum.photos/id/9/5000/3269",
    totaltimeloged: 678,
    currentStatus: 0,
  },
  {
    id: "11",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/Cm7oKel-X2Q",
    download_url: "https://picsum.photos/id/11/2500/1667",
    totaltimeloged: 234,
    currentStatus: 0,
  },

  {
    id: "12",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/I_9ILwtsl_k",
    download_url: "https://picsum.photos/id/12/2500/1667",
    totaltimeloged: 345,
    currentStatus: 1,
  },
  {
    id: "13",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/3MtiSMdnoCo",
    download_url: "https://picsum.photos/id/13/2500/1667",
    totaltimeloged: 234,
    currentStatus: 0,
  },
  {
    id: "14",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/IQ1kOQTJrOQ",
    download_url: "https://picsum.photos/id/14/2500/1667",
    totaltimeloged: 567,
    currentStatus: 1,
  },
  {
    id: "15",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/NYDo21ssGao",
    download_url: "https://picsum.photos/id/15/2500/1667",
    totaltimeloged: 456,
    currentStatus: 0,
  },
  {
    id: "16",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/gkT4FfgHO5o",
    download_url: "https://picsum.photos/id/16/2500/1667",
    totaltimeloged: 789,
    currentStatus: 1,
  },
  {
    id: "17",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/Ven2CV8IJ5A",
    download_url: "https://picsum.photos/id/17/2500/1667",
    totaltimeloged: 345,
    currentStatus: 0,
  },
  {
    id: "18",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/Ps2n0rShqaM",
    download_url: "https://picsum.photos/id/18/2500/1667",
    totaltimeloged: 678,
    currentStatus: 1,
  },
  {
    id: "19",
    Employee: "Paul Jarvis",
    width: 2500,
    height: 1667,
    url: "https://unsplash.com/photos/P7Lh0usGcuk",
    download_url: "https://picsum.photos/id/19/2500/1667",
    totaltimeloged: 567,
    currentStatus: 0,
  },
  {
    id: "20",
    Employee: "Aleks Dorohovich",
    width: 3670,
    height: 2462,
    url: "https://unsplash.com/photos/nJdwUHmaY8A",
    download_url: "https://picsum.photos/id/20/3670/2462",
    totaltimeloged: 456,
    currentStatus: 1,
  },
  {
    id: "21",
    Employee: "Alejandro Escamilla",
    width: 3008,
    height: 2008,
    url: "https://unsplash.com/photos/jVb0mSn0LbE",
    download_url: "https://picsum.photos/id/21/3008/2008",
    totaltimeloged: 567,
    currentStatus: 0,
  },
  // ... (similar modifications for other objects)
];
