export const ACTION_TYPES = {
  SHOW_HIDE_LOADER: "SHOW_HIDE_LOADER",
  SHOW_HIDE_SIDE_NAVIGATION: "SHOW_HIDE_SIDE_NAVIGATION",
  SET_USER_NAME: "SET_USER_NAME",
  SET_USER_ID: "SET_USER_ID",
  SET_USER_ROLE: "SET_USER_ROLE",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
};
